version: '3.9'

services:
  fastapi:
    build:
      context: ./fastapi_app
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
    ports:
      - "5000:5000"
    networks:
      - app-network

  streamlit:
    build:
      context: ./streamlit_app
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
    ports:
      - "8501:8501"
    networks:
      - app-network
    depends_on:
      - fastapi

networks:
  app-network:
    driver: bridge
